/// Commands exposed over Tauri IPC by `commands.rs`. Each entry gets
/// `allow-<command>` / `deny-<command>` permissions autogenerated into the
/// app ACL manifest (consumed by `capabilities/default.json`).
/// Keep in sync with `src/commands.rs::COMMAND_NAMES` — a unit test there
/// fails if the two lists drift apart.
const APP_COMMANDS: &[&str] = &[
    "list-sermons",
    "search-sermons",
    "create-sermon",
    "load-sermon",
    "save-sermon",
    "rename-sermon",
    "duplicate-sermon",
    "archive-sermon",
    "delete-sermon",
    "pin-sermon",
    "parse-references",
    "lint-sermon",
    "get-passage",
    "get-strongs",
    "get-cross-references",
    "get-preached-on",
    "sync-index",
    "rebuild-index",
    "rescan-library",
    "repair-index",
    "cancel-index-operation",
    "get-index-status",
    "get-archive-stats",
    "get-illustration-fatigue",
    "set-librarian-enabled",
    "create-export-snapshot",
    "execute-export-job",
    "export-sermon",
    "reveal-exported-file",
    "resolve-conflict",
    "prepare-diff",
    "prepare-merge",
    "get-filesystem-status",
    "recover-sermon",
    "reconnect-sermon",
    "load-settings",
    "save-settings",
    "test-directive-codec",
    "get-config",
    "set-config",
    "set-vault",
    "get-verse-words",
    "get-lexicon",
    "verses-for-strong",
    "cross-references",
    "sermons-for-verse",
    "librarian-catalog",
    "librarian-related",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
