/// Commands exposed over Tauri IPC by `commands.rs`. Each entry gets
/// `allow-<command>` / `deny-<command>` permissions autogenerated into the
/// app ACL manifest (consumed by `capabilities/default.json`).
/// Keep in sync with `src/commands.rs::COMMAND_NAMES` — a unit test there
/// fails if the two lists drift apart.
const APP_COMMANDS: &[&str] = &[
    "list_sermons",
    "search_sermons",
    "create_sermon",
    "load_sermon",
    "save_sermon",
    "rename_sermon",
    "duplicate_sermon",
    "archive_sermon",
    "delete_sermon",
    "pin_sermon",
    "parse_references",
    "lint_sermon",
    "get_passage",
    "get_strongs",
    "get_cross_references",
    "get_preached_on",
    "get_chain_study",
    "sync_index",
    "rebuild_index",
    "rescan_library",
    "repair_index",
    "cancel_index_operation",
    "get_index_status",
    "get_archive_stats",
    "get_illustration_fatigue",
    "get_related_sermons",
    "get_passage_history",
    "get_sermon_insights",
    "set_librarian_enabled",
    "create_export_snapshot",
    "execute_export_job",
    "export_sermon",
    "reveal_exported_file",
    "resolve_conflict",
    "prepare_diff",
    "prepare_merge",
    "get_filesystem_status",
    "recover_sermon",
    "reconnect_sermon",
    "load_settings",
    "save_settings",
    "test_directive_codec",
    "get_config",
    "set_config",
    "set_vault",
    "get_verse_words",
    "get_lexicon",
    "verses_for_strong",
    "cross_references",
    "sermons_for_verse",
    "librarian_catalog",
    "librarian_related",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
