/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    container: { center: true, padding: '1rem' },
    extend: {
      colors: {
        background: { DEFAULT: 'var(--bg)' },
        foreground: { DEFAULT: 'var(--fg)' },
        primary: { DEFAULT: 'var(--accent)', foreground: 'var(--bg)' },
        secondary: { DEFAULT: 'var(--elevated)', foreground: 'var(--fg-dim)' },
        accent: { DEFAULT: 'var(--accent)', foreground: 'var(--bg)' },
        'accent-2': { DEFAULT: 'var(--accent-2)' },
        muted: { DEFAULT: 'var(--panel)', foreground: 'var(--fg-dim)' },
        card: { DEFAULT: 'var(--panel)', foreground: 'var(--fg)' },
        border: { DEFAULT: 'var(--border)' },
        input: { DEFAULT: 'var(--elevated)' },
        ring: { DEFAULT: 'var(--accent)' },
        surface: {
          2: 'var(--panel)',
          3: 'var(--elevated)',
          4: 'var(--surface-4)',
        },
        'gold-light': 'var(--gold-light)',
        'gold-dark': 'var(--gold-dark)',
        'ref-blue': 'var(--accent)',
        'alert-red': 'var(--red-alert)',
        'warn-amber': 'var(--warn)',
        'ok-green': 'var(--accent-2)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        sm: 'calc(var(--radius) - 1px)',
        md: 'var(--radius)',
        lg: 'calc(var(--radius) + 3px)',
        xl: 'calc(var(--radius) + 7px)',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
        editor: ['var(--font-editor)', 'serif'],
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
        xs: ['11px', { lineHeight: '16px' }],
        sm: ['13px', { lineHeight: '18px' }],
        base: ['14px', { lineHeight: '20px' }],
        md: ['15px', { lineHeight: '22px' }],
        lg: ['16px', { lineHeight: '24px' }],
        xl: ['18px', { lineHeight: '26px' }],
        '2xl': ['20px', { lineHeight: '28px' }],
        '3xl': ['24px', { lineHeight: '32px' }],
        '4xl': ['30px', { lineHeight: '38px' }],
      },
      fontWeight: {
        '400': '400',
        '500': '500',
        '600': '600',
        '700': '700',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};